sonar.projectKey=pfe-mlops
sonar.qualitygate.wait=true
sonar.sources=mlops pipelines/components
sonar.tests=mlops pipelines/tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml
sonar.python.bandit.reportPaths=bandit-report.json